In [2]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
#from sklearn.datasets import load_iris

data = pd.read_csv('4.csv')

le = LabelEncoder()
data = data.apply(le.fit_transform)

x = np.array(data.iloc[:,0:-1])
y = np.array(data.iloc[:,-1])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state=1)

model = GaussianNB().fit(x_train,y_train)

y_pred = model.predict(x_test)

In [3]:
print(y_pred,y_test,sep='\n')

[1 1 0 1]
[1 1 1 1]


In [4]:

print(accuracy_score(y_pred,y_test))

0.75


In [7]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

data = pd.read_csv('4.csv')

le = LabelEncoder()
data= data.apply(le.fit_transform)

x=np.array(data.iloc[:,0:-1])
y=np.array(data.iloc[:,-1])

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=1)

model = GaussianNB().fit(x_train,y_train)
y_pred= model.predict(x_test)

print(y_pred,y_test,sep='\n')
print(accuracy_score(y_pred,y_test))

[1 1 0 1]
[1 1 1 1]
0.75


In [8]:
x = np.array(data.iloc[:,0:-1])
y=np.array(data.iloc[:,-1])